# Generated by Django 2.1.2 on 2020-03-31 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meet2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='PostCreationTime',
        ),
    ]
