# Generated by Django 2.1.2 on 2020-03-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet2', '0002_auto_20200318_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinterestedevents',
            name='EntryTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userinterestedevents',
            name='ExitTime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
