# Generated by Django 2.1.2 on 2020-03-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet2', '0003_auto_20200328_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='PhoneNumber',
            field=models.CharField(max_length=12),
        ),
    ]
