# Generated by Django 2.1.2 on 2020-03-29 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meet2', '0005_userpostlikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpostlikes',
            name='PostId',
        ),
        migrations.RemoveField(
            model_name='userpostlikes',
            name='UserId',
        ),
        migrations.DeleteModel(
            name='UserPostLikes',
        ),
    ]
