# Generated by Django 2.1.2 on 2020-03-29 18:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meet2', '0006_auto_20200329_2339'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupmembers',
            unique_together={('UserId', 'GroupId')},
        ),
        migrations.AlterUniqueTogether(
            name='hasevents',
            unique_together={('GroupId', 'EventId')},
        ),
        migrations.AlterUniqueTogether(
            name='hasposts',
            unique_together={('GroupId', 'PostId')},
        ),
        migrations.AlterUniqueTogether(
            name='phonenumber',
            unique_together={('UserId', 'PhoneNumber')},
        ),
        migrations.AlterUniqueTogether(
            name='userinterestedevents',
            unique_together={('UserId', 'EventId')},
        ),
    ]
